version: '3.8'

services:
  frontend:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: saas-frontend
    ports:
      - "4173:4173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
      - BACKEND_URL=http://localhost:2345
    networks:
      - saas-network
    restart: unless-stopped

networks:
  saas-network:
    name: saas-network
    driver: bridge 